### ISSUE TITLE
Oracle 12

### ISSUE THREAD

**Issue by mhiett** [azauditor/OracleAudit#1]
Inherited and Implicit are not available in Oracle Version 12, recommend removing reference in the Readme under the Oracle - Users and Account Status section.
Old:
SELECT USERNAME, USER_ID, ACCOUNT_STATUS, LOCK_DATE,
        EXPIRY_DATE, CREATED, EXTERNAL_NAME, PASSWORD_VERSIONS,
        EDITIONS_ENABLED, AUTHENTICATION_TYPE, PROXY_ONLY_CONNECT,
        COMMON, LAST_LOGIN, ORACLE_MAINTAINED, INHERITED, IMPLICIT
    FROM DBA_USERS
New:
SELECT USERNAME, USER_ID, ACCOUNT_STATUS, LOCK_DATE,
        EXPIRY_DATE, CREATED, EXTERNAL_NAME, PASSWORD_VERSIONS,
        EDITIONS_ENABLED, AUTHENTICATION_TYPE, PROXY_ONLY_CONNECT,
        COMMON, LAST_LOGIN, ORACLE_MAINTAINED
    FROM DBA_USERS

![Oracle12](https://user-images.githubusercontent.com/32172785/59046005-fcf3ef80-8835-11e9-83b5-0e827bab2c3b.png)

**Comment by aentringer** [comment]
Technically, it is available in 12, [depending on the version being discussed](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/refrn/DBA_USERS.html#GUID-309FCCB2-2E8D-4371-9FC5-7F3B10E2A8C0). The specific version has been clarified in the queries.
